package com.profa.auth;
import com.profa.user.*;import com.profa.security.JwtService;import com.profa.teacher.TeacherProfile;import com.profa.teacher.TeacherRepository;import com.profa.school.SchoolProfile;import com.profa.school.SchoolRepository;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.web.bind.annotation.*;import java.util.*;
import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/v1/auth") public class AuthController { private final UserRepository users;private final PasswordEncoder encoder;private final JwtService jwt;private final TeacherRepository teachers;private final SchoolRepository schools;
 public AuthController(UserRepository u,PasswordEncoder e,JwtService j,TeacherRepository t,SchoolRepository s){users=u;encoder=e;jwt=j;teachers=t;schools=s;}
 public record Register(@Email @NotBlank String email,@Size(min=8) String password,@NotBlank String firstName,@NotBlank String lastName,String phone,@NotNull Role role){} public record Login(@Email @NotBlank String email,@NotBlank String password){} public record AuthResponse(String token,String role,String firstName,String lastName){}
 @PostMapping("/register") public ResponseEntity<?> register(@Valid @RequestBody Register r){if(r.role()==Role.ADMIN)return ResponseEntity.status(403).body(Map.of("message","Admin creation is restricted"));if(users.findByEmailIgnoreCase(r.email()).isPresent())return ResponseEntity.badRequest().body(Map.of("message","Email already used"));User u=new User();u.setEmail(r.email().trim().toLowerCase());u.setPasswordHash(encoder.encode(r.password()));u.setFirstName(r.firstName());u.setLastName(r.lastName());u.setPhone(r.phone());u.setRole(r.role());users.save(u);if(r.role()==Role.TEACHER){TeacherProfile p=new TeacherProfile();p.setUserId(u.getId());teachers.save(p);}if(r.role()==Role.SCHOOL){SchoolProfile p=new SchoolProfile();p.setUserId(u.getId());schools.save(p);}return ResponseEntity.ok(new AuthResponse(jwt.generate(u),u.getRole().name(),u.getFirstName(),u.getLastName()));}
 @PostMapping("/login") public AuthResponse login(@Valid @RequestBody Login r){User u=users.findByEmailIgnoreCase(r.email()).orElseThrow();if(!encoder.matches(r.password(),u.getPasswordHash()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials");return new AuthResponse(jwt.generate(u),u.getRole().name(),u.getFirstName(),u.getLastName());}
}
